### PR TITLE
Updated design tokens (Bloom 3218)

### PR DESCRIPTION
**Pull request by jaredcwhite**
Implements the updates requested by bloom-housing/bloom#3218  and bloom-housing/bloom#3175 for the ui-components package. Another PR will be needed for Bloom core: bloom-housing/bloom#3289

**BREAKING CHANGE**  
Downstream consumers who make direct use of color and typography scale tokens will need to update their use these tokens:

**Font sizes**

- 6_5xl -> 6xl
- 6xl -> 5xl
- 5xl -> 4xl
- 4xl -> 3xl
- 3xl -> 2xl
- lg -> xl
- base-alt -> lg
- tiny -> sm
- sm -> xs
- xs -> 2xs
- 2xs -> 3xs

**Colors**

- swap `gray-950` for `gray-900`
- `blue-800` is now `blue-900`
- `blue-600` is now `blue-500`
- `blue-200` is now `blue-100`
- except for blue, previous `800` colors are now `700`, `700` are now `500`
- previous color tokens `lush`, `secondary`, and all `teal` colors have been removed

### CODE REVIEW

**Comment by jaredcwhite** [comment]
This now includes updates to a couple of gray colors as part of bloom-housing/bloom#3263

**Review by ludtkemorgan — APPROVED** [review]

**Review by ColinBuyck — DISMISSED** [review]
LGTM 🎨

**Review by ColinBuyck — APPROVED** [review]
So the changes all looks good to me! Just wanted to highlight that in order for the package to be versioned correctly we'll need have "BREAKING CHANGE: " in the **footer** of the commit message per this [discussion](https://stackoverflow.com/questions/70061964/semantic-release-doesnt-create-release-with-breaking-change) 🎨

**Comment by jaredcwhite** [comment]
Thanks @ColinBuyck for the reminder, that worked! BTW, I guess we'd decided on a more manual process for updating the Changelog but it doesn't looks like it's been updated in some time so I'm not sure what our process is yet for doing so…

**Pull request merged**
