### PR TITLE
fix: add variable width to description titles

### PR DESCRIPTION
**Pull request by chadbrokaw-exygy**
## Description

There are two issues within DAHLIA related to translations. The first is that, within the Contact component, we need to have the ability to pass a classname to the Contact Title element. This allows us to specifically target that element for machine translation.

The second issue related to the Description component. Currently, the widths of the term and definition column are hardcoded as 33% and 66%, respectively. However, there are instances (specifically at small screen widths) when a single word exceeds the width of the term column. For example, in English Appliances fits into the term column, but when translated to Spanish, this term becomes "Electrodomésticos" which would run over into the definition column. A fix for this is to use grid to allow the columns width to be flexible but also uniform across the different rows.

A third issue, unrelated to translations but important for DOM readability, is that in the Description component, the `dt` and `dd` tags should be flipped where the term element precedes the description element.

## How Can This Be Tested/Reviewed?

For testing the Contact component:
- Review the Contact component in Storybook and ensure that there are no visual differences. This change is to only allow for the addition of extra classnames to the title element.

For testing the Description component element switch (dt/dd):
- Review the Description component and ensure that there are no changes to the functionality / style-ability of the component. The only change to this component was switching element tags.

For testing the Description component styling changes:
- Check it out in DAHLIA and ensure that the words do not overrun each other even at smaller widths.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have added QA notes to the issue
- [x] I have performed a self-review of my own code
- [x] I have reviewed the changes in a desktop view
- [x] I have reviewed the changes in a mobile view
- [ ] I have made any corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added or updated stories if new changes are not captured in Storybook
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have exported any new pieces added to ui-components
- [ ] I have documented this change in the changelog, and any breaking changes are well described

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Either review the Storybook preview or pull the changes down locally and test that the acceptance criteria is met
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

On merge, squash commits.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
Screenshot 2023-02-01 at 3 32 29 PM
Screenshot 2023-02-01 at 3 32 21 PM

**Review by emilyjablonski — APPROVED** [review]
Looks great thank you!!

**Comment by emilyjablonski** [comment]
This also closes this Bloom issue: https://github.com/bloom-housing/bloom/issues/3215

**Review by ColinBuyck — APPROVED** [review]
LGTM 🦖

**Comment by ludtkemorgan** [comment]
@chadbrokaw-exygy looks like this PR has the proper approvals 🎉 .  I gave you "maintain" access to ui-components. You should be able to click the the merge button. Let me know if that is not the case. Make sure you click "Squash and merge" and the commit message follows the proper commit message format: https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format.

**Pull request merged**
